spring:
  application:
    name: wakfu-builder-backend
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

scheduling:
  game-data-sync-cron: "0 0 0 * * MON"

client:
  base-url: https://wakfu.cdn.ankama.com/gamedata/
  images:
    primary-url: https://static.ankama.com/wakfu/portal/game/item/115/
    secondary-url: https://vertylo.github.io/wakassets/items/
